language: ruby
rvm:
- ruby-head
- 2.1
- 2.0
- 1.9.3
- 1.9.2
- jruby-head
- jruby-1.7
- rbx
bundler_args: "--without development"
addons:
  code_climate:
    repo_token:
      secure: HdKw+GBs77+DnKb9oRTaARf8GuTAaKedEGvxh2W6z8NsxhbSVY5hJAYWdqg/8r2Aywqui7+8OH1bJ90PixipgJjIlDu8uamaiYfjScPMk5VPl0UOtOo/cAo4F79d1lHsbymtuoZI8Mat7FE0//d1QorruZ1lsXsKPrWWPi9byV0=
