language: ruby
rvm:
  - ruby-head
  - 2.1
  - 2.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - jruby-head
  - jruby-1.7
  - jruby-1.6
  - jruby-1.5
bundler_args: --without development
addons:
  code_climate:
    repo_token: cc41eb6449075390a8bdb804fa3ff5865a7fbf22384fcd1757730b702eefdb0a
